version: "2.3"

services:
    armai-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        network_mode: bridge
        environment:
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/armai/.ccache
          - CORES_DIR=/cores
        volumes:
          - .:/armai:rw
        ports:
          - 8080:8080
        working_dir: /armai
        entrypoint:
          - ./tests/run_as_user.sh
