port 26379
sentinel monitor test_master0 172.21.0.2 6379 1
sentinel auth-pass test_master0 admin
sentinel down-after-milliseconds test_master0 5000
sentinel failover-timeout test_master0 60000
sentinel parallel-syncs test_master0 1